Draw robot in the robot card
NAMeC-team/rbc24-aquarium pull request #5
Opened 2024-08-09 08:36 UTC by Jossl123

The robot shape is now drawn in the robot information cards.
The rectangle in the front of the bot turn red when "hasBall" is true.

2024-08-11 11:40 UTC, Wanchai290 approved these changes
j'ai pas review les maths mais codewise ça paraît nickel
peut-être que ça vaut le coup de typer les objets dans VISION_PATTERN_COLOR et détailler dans de la doc ton référentiel (`top_left`c'est quand le robot pointe en haut ?)

2024-08-11 11:40 UTC, Wanchai290 commented
faudrait check si ça crash pas avec un robot en moins ou qui disparaît/apparaît

2024-08-11 11:52 UTC, Wanchai290 requested changes
![image](https://github.com/user-attachments/assets/8a3b8213-6d61-49ae-b416-9c034577956d)
l'orientation a l'air symétriquement opposée, regarde l'orientation réelle du robot 0 et son orientation dans la carte

2024-08-19 15:36 UTC, Jossl123 commented
@Wanchai290 bien vu merci

2024-08-22 15:13 UTC, dalestee commented
Does it work when there is one or multiple missing bots?

2024-08-22 15:15 UTC, dalestee approved these changes
lgtm and it works.

2024-08-22 16:15 UTC, Wanchai290 approved these changes

2024-08-22 16:16 UTC, merged